// <auto-generated />
using System;
using EFOwned.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFOwned.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260311202130_UserOrdersBucketItems")]
    partial class UserOrdersBucketItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EFOwned.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EFOwned.Entities.User", b =>
                {
                    b.OwnsMany("EFOwned.Entities.Order", "Orders", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("OrderDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("order_date");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("orders", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("EFOwned.Entities.Bucket", "Bucket", b2 =>
                                {
                                    b2.Property<int>("OrderUserId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("OrderId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("TotalPrice")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("total_price");

                                    b2.HasKey("OrderUserId", "OrderId");

                                    b2.ToTable("orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderUserId", "OrderId");

                                    b2.OwnsMany("EFOwned.Entities.Item", "Items", b3 =>
                                        {
                                            b3.Property<int>("BucketOrderUserId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<int>("BucketOrderId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("INTEGER");

                                            b3.Property<int>("Price")
                                                .HasColumnType("INTEGER")
                                                .HasColumnName("price");

                                            b3.HasKey("BucketOrderUserId", "BucketOrderId", "Id");

                                            b3.ToTable("Item");

                                            b3.WithOwner()
                                                .HasForeignKey("BucketOrderUserId", "BucketOrderId");
                                        });

                                    b2.Navigation("Items");
                                });

                            b1.Navigation("Bucket")
                                .IsRequired();
                        });

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
