// <auto-generated />
using EFOwned.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFOwned.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260311095858_ManualKeys")]
    partial class ManualKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EFOwned.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EFOwned.Entities.User", b =>
                {
                    b.OwnsOne("EFOwned.Entities.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<int>("ManualKeyName")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("home_city");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("home_street");

                            b1.HasKey("ManualKeyName");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("ManualKeyName");
                        });

                    b.OwnsOne("EFOwned.Entities.Address", "WorkAddress", b1 =>
                        {
                            b1.Property<int>("ManualKeyName")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("work_city");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("work_street");

                            b1.HasKey("ManualKeyName");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("ManualKeyName");
                        });

                    b.Navigation("HomeAddress")
                        .IsRequired();

                    b.Navigation("WorkAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
