// <auto-generated />
using EFOwned.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFOwned.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EFOwned.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EFOwned.Entities.User", b =>
                {
                    b.OwnsOne("EFOwned.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("city");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("EFOwned.Entities.Country", "Country", b2 =>
                                {
                                    b2.Property<int>("AddressUserId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("country_name");

                                    b2.HasKey("AddressUserId");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressUserId");

                                    b2.OwnsOne("EFOwned.Entities.Continent", "Continent", b3 =>
                                        {
                                            b3.Property<int>("CountryAddressUserId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("TEXT")
                                                .HasColumnName("continent_name");

                                            b3.HasKey("CountryAddressUserId");

                                            b3.ToTable("users");

                                            b3.WithOwner()
                                                .HasForeignKey("CountryAddressUserId");

                                            b3.OwnsOne("EFOwned.Entities.Planet", "Planet", b4 =>
                                                {
                                                    b4.Property<int>("ContinentCountryAddressUserId")
                                                        .HasColumnType("INTEGER");

                                                    b4.Property<string>("Name")
                                                        .IsRequired()
                                                        .HasColumnType("TEXT")
                                                        .HasColumnName("planet_name");

                                                    b4.HasKey("ContinentCountryAddressUserId");

                                                    b4.ToTable("users");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ContinentCountryAddressUserId");

                                                    b4.OwnsOne("EFOwned.Entities.SolarSystem", "SolarSystem", b5 =>
                                                        {
                                                            b5.Property<int>("PlanetContinentCountryAddressUserId")
                                                                .HasColumnType("INTEGER");

                                                            b5.Property<string>("Name")
                                                                .IsRequired()
                                                                .HasColumnType("TEXT")
                                                                .HasColumnName("solar_system_name");

                                                            b5.HasKey("PlanetContinentCountryAddressUserId");

                                                            b5.ToTable("users");

                                                            b5.WithOwner()
                                                                .HasForeignKey("PlanetContinentCountryAddressUserId");

                                                            b5.OwnsOne("EFOwned.Entities.Galaxy", "Galaxy", b6 =>
                                                                {
                                                                    b6.Property<int>("SolarSystemPlanetContinentCountryAddressUserId")
                                                                        .HasColumnType("INTEGER");

                                                                    b6.Property<string>("Name")
                                                                        .IsRequired()
                                                                        .HasColumnType("TEXT")
                                                                        .HasColumnName("galaxy_name");

                                                                    b6.HasKey("SolarSystemPlanetContinentCountryAddressUserId");

                                                                    b6.ToTable("users");

                                                                    b6.WithOwner()
                                                                        .HasForeignKey("SolarSystemPlanetContinentCountryAddressUserId");

                                                                    b6.OwnsOne("EFOwned.Entities.Universe", "Universe", b7 =>
                                                                        {
                                                                            b7.Property<int>("GalaxySolarSystemPlanetContinentCountryAddressUserId")
                                                                                .HasColumnType("INTEGER");

                                                                            b7.Property<string>("Name")
                                                                                .IsRequired()
                                                                                .HasColumnType("TEXT")
                                                                                .HasColumnName("universe_name");

                                                                            b7.HasKey("GalaxySolarSystemPlanetContinentCountryAddressUserId");

                                                                            b7.ToTable("users");

                                                                            b7.WithOwner()
                                                                                .HasForeignKey("GalaxySolarSystemPlanetContinentCountryAddressUserId");

                                                                            b7.OwnsOne("EFOwned.Entities.Multiverse", "Multiverse", b8 =>
                                                                                {
                                                                                    b8.Property<int>("UniverseGalaxySolarSystemPlanetContinentCountryAddressUserId")
                                                                                        .HasColumnType("INTEGER");

                                                                                    b8.Property<string>("Name")
                                                                                        .IsRequired()
                                                                                        .HasColumnType("TEXT")
                                                                                        .HasColumnName("multiverse_name");

                                                                                    b8.HasKey("UniverseGalaxySolarSystemPlanetContinentCountryAddressUserId");

                                                                                    b8.ToTable("users");

                                                                                    b8.WithOwner()
                                                                                        .HasForeignKey("UniverseGalaxySolarSystemPlanetContinentCountryAddressUserId");

                                                                                    b8.OwnsOne("EFOwned.Entities.Hiperverse", "Hiperverse", b9 =>
                                                                                        {
                                                                                            b9.Property<int>("ManualKeyName")
                                                                                                .HasColumnType("INTEGER");

                                                                                            b9.Property<string>("Name")
                                                                                                .IsRequired()
                                                                                                .HasColumnType("TEXT")
                                                                                                .HasColumnName("hiperverse_name");

                                                                                            b9.HasKey("ManualKeyName");

                                                                                            b9.ToTable("users");

                                                                                            b9.WithOwner()
                                                                                                .HasForeignKey("ManualKeyName");
                                                                                        });

                                                                                    b8.Navigation("Hiperverse")
                                                                                        .IsRequired();
                                                                                });

                                                                            b7.Navigation("Multiverse")
                                                                                .IsRequired();
                                                                        });

                                                                    b6.Navigation("Universe")
                                                                        .IsRequired();
                                                                });

                                                            b5.Navigation("Galaxy")
                                                                .IsRequired();
                                                        });

                                                    b4.Navigation("SolarSystem")
                                                        .IsRequired();
                                                });

                                            b3.Navigation("Planet")
                                                .IsRequired();
                                        });

                                    b2.Navigation("Continent")
                                        .IsRequired();
                                });

                            b1.Navigation("Country")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
